const faker = require('faker');

const MOCK_PHONES = [
    {
        availability: 5,
        brand: 'apple',
        description: faker.lorem.sentences(2),
        id: 'bfaf91b1',
        image: 'phone_bfaf91b1.png',
        name: 'iPhone 128GB',
        price: 569,
        ratingValue: 4.5,
        reviewCount: 93,
        sku: faker.datatype.uuid(),
        phoneProp: 'phone',
    },
    {
        availability: 0,
        brand: 'apple',
        description: faker.lorem.sentences(2),
        id: '48e51f536c8a',
        image: 'phone_48e51f536c8a.png',
        name: 'iPhone 12x Pro 256GB',
        price: 1379,
        ratingValue: 4.82,
        reviewCount: 245,
        sku: faker.datatype.uuid(),
        phoneProp: 'phone',
    },
    {
        availability: 240,
        brand: 'huawei',
        description: faker.lorem.sentences(2),
        id: 'b20f6529',
        image: 'phone_b20f6529.png',
        name: 'HUAWEI P Smart 2021 Midnight Black',
        price: 199,
        ratingValue: 3.7,
        reviewCount: 313,
        sku: faker.datatype.uuid(),
        phoneProp: 'phone',
    },
    {
        availability: 21,
        brand: 'samsung',
        description: faker.lorem.sentences(2),
        id: 'd9ec258c6660',
        image: 'phone_d9ec258c6660.png',
        name: 'SAMSUNG Galaxy A52s Dual 5G 256GB',
        price: 539.9,
        ratingValue: 4.1,
        reviewCount: 67,
        sku: faker.datatype.uuid(),
        phoneProp: 'phone',
    },
    {
        availability: 5,
        brand: 'apple',
        description: faker.lorem.sentences(2),
        id: 'bfaf91b1a',
        image: 'phone_bfaf91b1.png',
        name: 'iPhone 11s 128GB',
        price: 569,
        ratingValue: 4.5,
        reviewCount: 93,
        sku: faker.datatype.uuid(),
        phoneProp: 'phone',
    },
    {
        availability: 56,
        brand: 'xiaomi',
        description: faker.lorem.sentences(2),
        id: '37595f12402b',
        image: 'phone_37595f12402b.png',
        name: 'Redmi 9C 32GB',
        price: 139.9,
        ratingValue: 4.03,
        reviewCount: 456,
        sku: faker.datatype.uuid(),
        phoneProp: 'phone',
    },
    {
        availability: 56,
        brand: 'xiaomi',
        description: faker.lorem.sentences(2),
        id: '37595f12402ba',
        image: 'phone_37595f12402b.png',
        name: 'Redmi 9C pro 32GB',
        price: 139.9,
        ratingValue: 4.03,
        reviewCount: 456,
        sku: faker.datatype.uuid(),
        phoneProp: 'phone',
    },
    {
        availability: 240,
        brand: 'huawei',
        description: faker.lorem.sentences(2),
        id: 'b20f6529a',
        image: 'phone_b20f6529.png',
        name: 'HUAWEI P Smart 2021 Midnight Black',
        price: 199,
        ratingValue: 3.7,
        reviewCount: 313,
        sku: faker.datatype.uuid(),
        phoneProp: 'phone',
    },
    {
        availability: 0,
        brand: 'apple',
        description: faker.lorem.sentences(2),
        id: '48e51f536c8ac',
        image: 'phone_48e51f536c8a.png',
        name: 'iPhone 12 Pro 256GB',
        price: 1000,
        ratingValue: 4.82,
        reviewCount: 245,
        sku: faker.datatype.uuid(),
        phoneProp: 'phone',
    },
    {
        availability: 100,
        brand: 'apple',
        description: faker.lorem.sentences(3),
        id: '48e51f536c8dd',
        image: 'iphone-13-pro-family-hero.png',
        name: 'iPhone 13',
        price: 1300,
        ratingValue: 4.85,
        reviewCount: 14,
        sku: faker.datatype.uuid(),
        phoneProp: 'phone',
    },
];

module.exports = { MOCK_PHONES };
