const faker = require('faker');

const MOCK_PHONES = [
    {
        availability: 5,
        brand: 'apple',
        description: faker.lorem.sentences(2),
        id: 'bfaf91b1',
        image: 'phone_bfaf91b1',
        name: 'iPhone SE 128GB',
        price: 569,
        ratingValue: 4.5,
        reviewCount: 93,
        sku: faker.datatype.uuid(),
        phoneProp: 'phone',
    },
    {
        availability: 0,
        brand: 'apple',
        description: faker.lorem.sentences(2),
        id: '48e51f536c8a',
        image: 'phone_48e51f536c8a',
        name: 'iPhone 12 Pro 256GB',
        price: 1379,
        ratingValue: 4.82,
        reviewCount: 245,
        sku: faker.datatype.uuid(),
        phoneProp: 'phone',
    },
    {
        availability: 240,
        brand: 'huawei',
        description: faker.lorem.sentences(2),
        id: '48e51f536c8a',
        image: 'phone_b20f6529',
        name: 'HUAWEI P Smart 2021 Midnight Black',
        price: 199,
        ratingValue: 3.7,
        reviewCount: 313,
        sku: faker.datatype.uuid(),
        phoneProp: 'phone',
    },
    {
        availability: 21,
        brand: 'samsung',
        description: faker.lorem.sentences(2),
        id: 'd9ec258c6660',
        image: 'phone_d9ec258c6660',
        name: 'SAMSUNG Galaxy A52s Dual 5G 256GB',
        price: 539.9,
        ratingValue: 4.1,
        reviewCount: 67,
        sku: faker.datatype.uuid(),
        phoneProp: 'phone',
    },
    {
        availability: 0,
        brand: 'samsung',
        description: faker.lorem.sentences(2),
        id: '8af4e66e',
        image: 'phone_8af4e66e',
        name: 'SAMSUNG Galaxy Z Flip',
        price: 1599.9,
        ratingValue: 4.54,
        reviewCount: 98,
        sku: faker.datatype.uuid(),
        phoneProp: 'phone',
    },
    {
        availability: 56,
        brand: 'xiaomi',
        description: faker.lorem.sentences(2),
        id: '37595f12402b',
        image: 'phone_37595f12402b',
        name: 'Redmi 9C 32GB',
        price: 139.9,
        ratingValue: 4.03,
        reviewCount: 456,
        sku: faker.datatype.uuid(),
        phoneProp: 'phone',
    },
];

module.exports = { MOCK_PHONES };
